config/routes.rb
Rails.application.routes.draw do

  get 'get_sub', to: 'subscribe_notification#index', as: 'get_notification'

  resources :novels, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :comics, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :subscribes, only: [:index, :destroy]

  resources :chapters, only: [:show]

  resources :categories, only: [:show, :index]

  resources :authors, only: [:show]

  get 'profile', to: 'sessions#show', as: 'profile'
  get 'signup', to: 'users#new', as: 'get_signup'
  post 'signup', to: 'users#create', as: 'post_signup'

  get 'login', to: 'sessions#new', as: 'get_login'
  post 'login', to: 'sessions#create', as: 'post_login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, except: [:index, :show]

  get '/', to: 'home#index', as: 'root'

  get 'search', to: 'search#index', as: 'search'


  namespace :admin do
    resources :authors, only: [:new, :create]
    resources :categories, only: [:create]

    resources :novels, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

    resources :comics, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

  end

end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :reviews, as: :reading
  has_many :subscribes, as: :reading
  has_many :author_readings, as: :reading
  has_many :category_readings, as: :reading
  has_many :chapters, as: :reading
  has_many :authors, :through => :author_readings
  has_many :categories, :through => :category_readings

  has_attached_file :cover, styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  scope :search, -> (keyword) { where("title LIKE ?" , "%#{keyword}%") }

  validates :title, presence: true, allow_blank: false

  def add_author(author)
    authors << author unless authors.include?(author)
  end

  def add_category(category)
    categories << category unless categories.include?(category)
  end

  def viewed
    chapters.sum(:viewed)
  end

  def vote
    reviews.average(:vote)
  end

end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < Admin::AdminController
  def index
    @comics = Comic.order('id DESC').page(params[:page]).per(30)
  end

  def new
    @comic = Comic.new
    @category = Category.new
    @author = Author.new
    @categories = Category.all
    @authors = Author.all
  end
  
  def create
    comic_params = params.require('comic').permit(:title, :description, :cover)
    @comic = Comic.new(comic_params)

    if @comic.save
      # add category and author
      if params[:authors]
        params[:authors].each do |au_id|
          if Author.exists?(au_id)
            author = Author.find(au_id)
            @comic.add_author(author)
          end
        end
      end

      if params[:categories]
        params[:categories].each do |cat_id|
          if Category.exists?(cat_id)
            cat = Category.find(cat_id)
            @comic.add_category(cat)
          end
        end
      end

      redirect_to admin_comics_path
    else
      @category = Category.new
      @author = Author.new
      @categories = Category.all
      @authors = Author.all
      render 'admin/comics/new'
    end
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    if params.has_key?(:page)
      @comics = Comic.order('id DESC').page(params[:page]).per(20)
    else
      @comics = Comic.order('id DESC').page(1).per(20)
    end
  end

  def show
    @comic = Comic.find params[:id]
  end
end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/views/comics/index.html.erb
<div class="container read">

  <%= render partial: 'layouts/comics', locals: {comics: @comics} %>

  <div class="text-center">
    <%= paginate @comics %>
  </div>


</div>

app/views/comics/show.html.erb
<div class="container read">

  <div class="row">
    <div class="col-xs-2">
      <div class="reading-cover">
        <% if @comic.cover.exists? %>
            <%= image_tag @comic.cover.url %>
        <% else %>
            <img src="/images/not-found.jpg" alt="Comic cover">
        <% end %>
        <% if logged_in? %>
            <div class="subscribe-box text-center">
              Subscribe


              <%= link_to comic_subscribes_url(@comic), method: :post do %>

                  <span class="glyphicon glyphicon-plus"></span>

              <% end %>
            </div>

        <% end %>
      </div>
    </div>

    <div class="col-xs-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @comic.title %></h3>


        </div>
        <div class="panel-body">

          <% if @comic.authors.blank? %>

          <% else %>
              <p>Author:

                <% @comic.authors.each do |author| %>

                    <%= link_to author.name, author_path(author) %>

                <% end %>

              </p>

          <% end %>

          <% if @comic.categories.blank? %>

          <% else %>
              <p>Categories:

                <% @comic.categories.each do |category| %>

                    <%= link_to category.title, category_path(category) %>

                <% end %>

              </p>

          <% end %>
        </div>

        <div class="panel-heading">
          <h3 class="panel-title">
            Description
          </h3>
        </div>

        <div class="panel-body">
          <%= @comic.description %>
        </div>


      </div>
    </div>
  </div>


  <% if @comic.chapters.blank? %>

      There is no chapters


  <% else %>
      <table class="table">
        <thead>
        <tr>
          <th>No.</th>
          <th>Title</th>
          <th>View</th>
        </tr>
        </thead>
        <tbody>
        <% @comic.chapters.order('id DESC').each do |chapter| %>


            <tr class="clickable-row" data-link=<%= chapter_path(chapter) %>>
              <td scope="row">


                <%= chapter.no %>


              </td>

              <td scope="row">


                <div class="reading-title">
                  <%= chapter.title %>
                </div>


              </td>

              <td scope="row">


                <div class="reading-title">
                  <%= chapter.viewed %>
                </div>


              </td>


            </tr>


        <% end %>


        </tbody>
      </table>


  <% end %>

  <div class="row">

    <h3>Review</h3>

    <% if logged_in? %>

        <div class="review-form">
          <%= form_tag comic_reviews_path(@comic), {:class => 'form'} do %>

              <div class="form-row">
                <%= label_tag :vote %>
                <%= number_field_tag :vote, min: 0, max: 10 %>
              </div>

              <div class="form-row">
                <%= label_tag :review %>
                <%= text_area_tag :review, nil, placeholder: 'Enter review', class: 'input' %>
              </div>
              <div class="form-row">
                <%= submit_tag 'Add Review', class: 'btn btn-large btn-primary' %>
              </div>
          <% end %>
        </div>
    <% end %>


    <% if @comic.reviews.blank? %>


    <% else %>

        <div class="reviews">
          <% @comic.reviews.each do |review| %>

              <div class="review">

                <div class="review-box">

                  <div class="review-text">
                    <%= review.review %>

                    <span class="review-vote">
                       <%= review.vote %>
                    </span>

                  </div>
                  <div class="review-footer">
                    <div class="review-info">
                      <span class="review-author">
                              <%= review.user.name %>
                      </span>
                      <span class="review-date">
                        <%= review.created_at %>
                      </span>
                    </div>

                    <% if current_user?(review.user) or current_user.is_admin? %>

                        <div class="review-actions">
                          <%= link_to review_path(review), method: :delete, data: {confirm: 'Are You Sure?'} do %>
                              <span class='glyphicon glyphicon-trash'></span>
                          <% end %>
                        </div>

                    <% end %>

                  </div>

                </div>

              </div>

          <% end %>
        </div>


    <% end %>

  </div>

</div>