config/routes.rb
Rails.application.routes.draw do

  get 'get_sub', to: 'subscribe_notification#index', as: 'get_notification'

  resources :novels, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :comics, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :subscribes, only: [:index, :destroy]

  resources :chapters, only: [:show]

  resources :categories, only: [:show, :index]

  resources :authors, only: [:show]

  get 'profile', to: 'sessions#show', as: 'profile'
  get 'signup', to: 'users#new', as: 'get_signup'
  post 'signup', to: 'users#create', as: 'post_signup'

  get 'login', to: 'sessions#new', as: 'get_login'
  post 'login', to: 'sessions#create', as: 'post_login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, except: [:index, :show]

  get '/', to: 'home#index', as: 'root'

  get 'search', to: 'search#index', as: 'search'


  namespace :admin do
    resources :authors, only: [:new, :create]
    resources :categories, only: [:create]

    resources :novels, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

    resources :comics, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @categories = Category.all

    @novels = Novel.order('id DESC').page(1).per(15)
    @comics = Comic.order('id DESC').page(1).per(15)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container read">

  <div class="row">
    <div class="col-xs-10 col-md-10">

      <%= render partial: 'layouts/comics', locals: {comics: @comics} %>

      <div class="text-center">
        <%= link_to 'Load all comic', comics_path %>
      </div>



      <%= render partial: 'layouts/novels', locals: {novels: @novels} %>

      <div class="text-center">
        <%= link_to 'Load all novel', novels_path %>
      </div>


    </div>

      <div class="col-xs-2 col-md-2">
        <div class="categories text-center">
          <div class="categories-header">
            Category
          </div>

          <% @categories.each do |category| %>

              <div class="category">

                <%= link_to category.title, category_path(category) %>

              </div>


          <% end %>


        </div>
      </div>





  </div>

</div>