config/routes.rb
Rails.application.routes.draw do

  get 'get_sub', to: 'subscribe_notification#index', as: 'get_notification'

  resources :novels, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :comics, only: [:index, :show] do
    resources :subscribes, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :subscribes, only: [:index, :destroy]

  resources :chapters, only: [:show]

  resources :categories, only: [:show, :index]

  resources :authors, only: [:show]

  get 'profile', to: 'sessions#show', as: 'profile'
  get 'signup', to: 'users#new', as: 'get_signup'
  post 'signup', to: 'users#create', as: 'post_signup'

  get 'login', to: 'sessions#new', as: 'get_login'
  post 'login', to: 'sessions#create', as: 'post_login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, except: [:index, :show]

  get '/', to: 'home#index', as: 'root'

  get 'search', to: 'search#index', as: 'search'


  namespace :admin do
    resources :authors, only: [:new, :create]
    resources :categories, only: [:create]

    resources :novels, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

    resources :comics, only: [:new, :create, :show, :index] do
      resources :chapters, only: [:new, :create, :index]
    end

  end

end

app/models/novel.rb
class Novel < ApplicationRecord
  has_many :reviews, as: :reading
  has_many :subscribes, as: :reading
  has_many :author_readings, as: :reading
  has_many :category_readings, as: :reading
  has_many :chapters, as: :reading
  has_many :authors, :through => :author_readings
  has_many :categories, :through => :category_readings
  scope :search, -> (keyword) { where("title LIKE ?" , "%#{keyword}%") }

  has_attached_file :cover, styles: {
      thumb: '100x100>',
      square: '200x200#',
      medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true, allow_blank: false

  def add_author(author)
    authors << author unless authors.include?(author)
  end

  def add_category(category)
    categories << category unless categories.include?(category)
  end

  def viewed
    chapters.sum(:viewed)
  end

  def vote
    reviews.average(:vote)
  end

end

app/controllers/admin/novels_controller.rb
class Admin::NovelsController < Admin::AdminController
  def new
    @novel = Novel.new
    @category = Category.new
    @author = Author.new
    @categories = Category.all
    @authors = Author.all
  end

  def create
    novel_params = params.require('novel').permit(:title, :description, :cover)
    @novel = Novel.new(novel_params)

    if @novel.save
      # add category and author
      if params[:authors]
        params[:authors].each do |au_id|
          if Author.exists?(au_id)
            author = Author.find(au_id)
            @novel.add_author(author)
          end
        end
      end

      if params[:categories]
        params[:categories].each do |cat_id|
          if Category.exists?(cat_id)
            cat = Category.find(cat_id)
            @novel.add_category(cat)
          end
        end
      end
      redirect_to admin_novels_path
    else
      @category = Category.new
      @author = Author.new
      @categories = Category.all
      @authors = Author.all
      render 'admin/novels/new'
    end
  end

  def index
    @novels = Novel.order('id DESC').page(params[:page]).per(30)
  end

end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  def index
    if params.has_key?(:page)
      @novels = Novel.order('id DESC').page(params[:page]).per(20)
    else
      @novels = Novel.order('id DESC').page(1).per(20)
    end
  end

  def show
    @novel = Novel.find params[:id]
  end
end

app/helpers/admin/novels_helper.rb
module Admin::NovelsHelper
end

app/views/admin/novels/create.html.erb
<h1>Admin::Novels#create,</h1>
<p>Find me in app/views/admin/novels/create,.html.erb</p>

app/views/admin/novels/delete.html.erb
<h1>Admin::Novels#delete</h1>
<p>Find me in app/views/admin/novels/delete.html.erb</p>

app/views/admin/novels/edit.html.erb
<h1>Admin::Novels#edit,</h1>
<p>Find me in app/views/admin/novels/edit,.html.erb</p>

app/views/admin/novels/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3 col-md-2">
      <ul>
        <li>
          <%= link_to "Novels", admin_novels_path %>
        </li>
      </ul>
    </div>
    <div class="col-xs-9 col-md-10">
      <h2>Novel Manager</h2>
      <div class="row">
        <div class="col-xs-12">
          <div class="pull-left">
            <form class="form-inline">
              <div class="form-group">
                <input type="text" class="form-control dashboard-search" name="keyword" placeholder="Search a user by name or email">
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            </form>
          </div>
          <div class="pull-right">
            <%= link_to new_admin_novel_path do %>
              <button type="button" class="btn btn-success">New Novel</button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="dashboard-table">
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>...</th>
          </tr>
          </thead>
          <tbody>
            <% @novels.each do |novel| %>
              <tr class='clickable-row' data-link="<%= admin_novel_chapters_path(novel) %>">
                <td><%= novel.title %></td>
                <td><%= novel.description.truncate(50) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= will_paginate @novels %>
    </div>
  </div>
</div>

app/views/admin/novels/new.html.erb
<div class="container">
  <% provide(:title, "New book") %>
  <% provide(:button_text, 'Submit') %>
  <h2>Add new novel</h2>
  <%= form_for @novel, url: admin_novels_path, :multipart => true do |f| %>
      <%= render partial: 'shared/err', locals: {err: @novel} %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label>Author</label><br>
        <div class="row">
          <% @authors.each do |author| %>
              <div class="col-xs-3">
                <input type="checkbox" name="authors[]" value="<%= author.id %>"><%= author.name %>
              </div>
          <% end %>
          <div class="col-xs-12" id="add-author-btn">
            <input type="button" class="btn btn-success" value="Add Author"
                      data-toggle="modal" data-target="#add-author-modal">
          </div>
        </div>
      </div>

      <div class="form-group">
        <label>Category</label><br>
        <div class="row">
          <% @categories.each do |category| %>
              <div class="col-xs-3">
                <input type="checkbox" name="categories[]" value="<%= category.id %>"><%= category.title %>
              </div>
          <% end %>
          <div class="col-xs-12" id="add-category-btn">
            <input type="button" class="btn btn-success" value="Add Category"
                     data-toggle="modal" data-target="#add-category-modal">
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :cover %>
        <%= f.file_field :cover, accept: 'image/png,image/gif,image/jpeg', class: 'form-control' %>
      </div>

      <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      </div>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>


<!-- Author Modal -->
<div id="add-author-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add new author</h4>
      </div>
      <div class="modal-body">
        <%= form_for @author, remote: true, url: admin_authors_path do |f| %>
          <div class="form-group">
            <%= f.label :name%>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :bio %>
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
            <div class="error-container">

            </div>
          <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<!-- Category Modal -->
<div id="add-category-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New category</h4>
      </div>
      <div class="modal-body">

        <%= form_for @category, remote: true, url: admin_categories_path do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/admin/novels/update.html.erb
<h1>Admin::Novels#update,</h1>
<p>Find me in app/views/admin/novels/update,.html.erb</p>